#!/usr/bin/env ruby

require "bundler/setup"
require 'thor'
require "json/search"

class CLI < Thor
  option :field, type: :string, desc: "Refers to the key to search for"
  option :file_path, type: :string, desc: "File path option requires absolute path"
  option :url, type: :string, desc: "The url option expects a valid url"
  desc "search KEYWORD", "Search and return records with names partially matching a given search query"
  def search(keyword = nil)
    object = Json::Search.new(**options)
    result = object.search(keyword)

    puts result
  rescue StandardError => e
    STDERR.puts e.message.capitalize
    exit 1
  end

  desc "duplicate_email", "Show any records having duplicate email"
  def duplicate_email
    result = Json::Search.new.duplicate_email

    puts result
  rescue StandardError => e
    STDERR.puts e.message.capitalize
    exit 1
  end
end

CLI.start(ARGV)
