#!/usr/bin/env ruby

require "bundler/setup"
require 'thor'
require "json/search"

class CLI < Thor
  option :field, type: :string
  option :file_path, type: :string
  desc "search KEYWORD --field FIELD --file_path FILE_ABSOLUTE_PATH", "Search and return records with names partially matching a given search query"
  def search(keyword = nil)
    object = Json::Search.new(field: options[:field], file_path: options[:file_path])
    result = object.search(keyword)

    puts result
  rescue StandardError => e
    STDERR.puts e.message.capitalize
    exit 1
  end

  desc "duplicate_email", "Show any records having duplicate email"
  def duplicate_email
    result = Json::Search.new.duplicate_email

    puts result
  rescue StandardError => e
    STDERR.puts e.message.capitalize
    exit 1
  end
end

CLI.start(ARGV)
